### ISSUE TITLE
AttributeError: 'MainApp' object has no attribute 'async_run'

### ISSUE THREAD

**Issue by LucaRicardo** [ComradOrg/Comrad#19]
I get this error when I try to run it with `./run.sh`

I'm using arch linux and Python 3.8.5

Here is the entire error
`User@Host ~/git/Komrade/app (git)-[master] % ./run.sh       `
`[INFO   ] [Logger      ] Record log in /home/lr/.kivy/logs/kivy_20-08-29_3.txt`
`[INFO   ] [Kivy        ] v1.11.1`
`[INFO   ] [Kivy        ] Installed at "/usr/lib/python3.8/site-packages/kivy/__init__.py"`
`[INFO   ] [Python      ] v3.8.5 (default, Jul 27 2020, 08:42:51) `
`[GCC 10.1.0]`
`[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"`
`[INFO   ] [Factory     ] 184 symbols loaded`
`[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)`
`[INFO   ] [KivyMD      ] v0.104.1`
`[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)`
`[INFO   ] [GL          ] Using the "OpenGL" graphics system`
`[INFO   ] [GL          ] Backend used <sdl2>`
`[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 20.1.6'>`
`[INFO   ] [GL          ] OpenGL vendor <b'Intel'>`
`[INFO   ] [GL          ] OpenGL renderer <b'Mesa Intel(R) UHD Graphics 620 (WHL GT2)'>`
`[INFO   ] [GL          ] OpenGL parsed version: 4, 6`
`[INFO   ] [GL          ] Shading version <b'4.60'>`
`[INFO   ] [GL          ] Texture max size <16384>`
`[INFO   ] [GL          ] Texture max units <32>`
`[INFO   ] [Window      ] auto add sdl2 input provider`
`[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked`
`[INFO   ] [Text        ] Provider: sdl2(['text_pango'] ignored)`
`[INFO   ] [GL          ] NPOT texture support is available`lr
 `[2020-08-29 19:09:57,292]`
 `connecting...`
 ``
 `[2020-08-29 19:09:57,294]`
 `starting server..`
 ``
 `[2020-08-29 19:09:57,294]`
 `/home/lr/git/Komrade/app`
 ``
 `[2020-08-29 19:09:57,294]`
 `listening..`
 ``
 `[2020-08-29 19:09:57,294]`
 `Node 420120771578343431675849077283393424863809941347 listening on 0.0.0.0:5639`
 ``
 `[2020-08-29 19:09:57,294]`
 `Refreshing routing table`
 ``
 `[2020-08-29 19:09:57,295]`
 `bootstrapping server..`
 ``
` [2020-08-29 19:09:57,295]`
` Attempting to bootstrap node with %i initial contacts 2`
` 
` Traceback (most recent call last):`
`   File "main.py", line 478, in <module>`
`     loop.run_until_complete(MainApp().app_func())`
`   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete`
`     return future.result()`
`   File "main.py", line 441, in run_wrapper`
`     await self.async_run() #async_lib='asyncio')`
` AttributeError: 'MainApp' object has no attribute 'async_run'`

Sorry for the weird formation

**Comment by quadrismegistus** [comment]
Thanks for trying to install it! I believe you need to run it with Python 3.7, not 3.8 (a bizarre requirement from Kivy). Also make sure to install the github version of Kivy  (pip install git+http://github.com/kivy/kivy) to get the version which has asyncio support. Let me know if this works?

**Comment by LucaRicardo** [comment]
It didn't work, same error

**Comment by quadrismegistus** [comment]
Hm, can't quite replicate it but will keep looking. Out of town until Monday so may take me a few days: be back in a bit

**Comment by LucaRicardo** [comment]
I re downloaded the code now and then runned the bootstrap script which fixed the previous error, but now it's complaining about not finding a module named 'pythemis' and after I installed it with pip it started working so I think you need to add pythemis to the requirements.txt

**Comment by quadrismegistus** [comment]
By the way, if anyone's still getting this error, see if the new installation instructions help get the right version of Kivy installed:

https://github.com/Komrade/Komrade#install

Front end is still mostly broken, but coming back to it now.
