### ISSUE TITLE
Conceptual Issue: Is the letter "K" too problematic? Thoughts on name of app?

### ISSUE THREAD

**Issue by marxzuckerburg** [ComradOrg/Comrad#30]
I mean... do people like the name? We could also try "comrad" or something...

**Comment by gary-host-laptop** [comment]
Do you mean problematic because of associations with certain racist groups? If that's so, I don't think so. Another name may be an option, too, not saying I don't like Komrade, just that it's an option.

**Comment by marxzuckerburg** [comment]
Yeah, that's what I meant. And I agree that another name is still possible: "komrade" was just available as a domain name, lol.

**Comment by gary-host-laptop** [comment]
I think that a name change should be first be considered as a whole transformation to the aesthetics of the project, like the use_your_imagination user commented, everything has like a post-ironic cold war vibe, and the name adds to that. Would the name change move towards something more serious? Would it move to a more "modern" aspect?

**Comment by marxzuckerburg** [comment]
I like the playfulness of it so far: it reminds you that nobody's making money off of this, lol. But that's just me, and I'm not sure how other people feel and how best to frame it all. Half the people [on r/privacy post comments](https://www.reddit.com/r/privacy/comments/ii4zw9/introducing_komrade_a_decentralized/) hated the name and design, half loved it. I don't mind turning non-comrades away, but we don't want to turn comrades away, either.

**Comment by marxzuckerburg** [comment]
As an example of what I mean, here's a kinda weird message I got from a friend of mine:

> btw i tried to download your social network (cool idea) and didn’t work bc of shell command issues. i think it has something to do with the fact that you named your app comrade-with-k. fascistic plus misogynist overtones but hard coding sensibility = exclusionary.

**Comment by marxzuckerburg** [comment]
What about "comrad"? "comrad.app" is available. (**Update**: I just bought it, just in case.) "Com" is kinda cute how it's both communication, a "com" channel, as well as camaraderie and "comrade". "rad" is kinda dumb though: "rad" was silly 90s way to say "cool".

Here's a poll to start thinking about it? Should we post this somewhere?

[![](https://api.gh-polls.com/poll/01EKC90BJ7TP51KJ87MXBZ2NTF/Komrade)](https://api.gh-polls.com/poll/01EKC90BJ7TP51KJ87MXBZ2NTF/Komrade/vote)
[![](https://api.gh-polls.com/poll/01EKC90BJ7TP51KJ87MXBZ2NTF/Comrad)](https://api.gh-polls.com/poll/01EKC90BJ7TP51KJ87MXBZ2NTF/Comrad/vote)
[![](https://api.gh-polls.com/poll/01EKC90BJ7TP51KJ87MXBZ2NTF/Comrade)](https://api.gh-polls.com/poll/01EKC90BJ7TP51KJ87MXBZ2NTF/Comrade/vote)
[![](https://api.gh-polls.com/poll/01EKC90BJ7TP51KJ87MXBZ2NTF/Other)](https://api.gh-polls.com/poll/01EKC90BJ7TP51KJ87MXBZ2NTF/Other/vote)

**Comment by marxzuckerburg** [comment]
More and more I'm liking Comrad. "Com"munication, "rad"ical communication, avoids "k", simple, ...

**Comment by quadrismegistus** [comment]
Ok, we're gonna try out Comrad for now (this was also [discussed on the Matrix chatroom](https://matrix.to/#/#komrade:matrix.org)), but we can always change the name over again. Closing issue for now
